# Andrew Disley: Front-end Skeleton
# http://github.com/andrewdisley/front-end-skeleton

# Minimal configuration see https://github.com/mojombo/jekyll/wiki/Configuration for full options

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:title

# Author
author: "Andrew Disley"
author_url: "http://simplified.co.uk/"
author_twitter: http://twitter.com/andrewdisley

# Site Title, Site Name (used for compressed js) Site ID (used on <body> element), Domain, URLs, Google Analytics ID
title: "North West Digital Communities"
name: "NWDC"
id: nwdc
domain: nwdc.org.uk
url: /
#assets_url: /
#assets_cache_buster: ?v=0.1
#google_analytics_id: UA-XXXXX-XX

# Set the environment used to include production specific assets and enable Google Analytics
# dev, sta, prd
env: prd

# Excluded files, jekyll excludes files that begin with an underscore
exclude: ['.htaccess', 'README', 'Rakefile']